### ISSUE TITLE
Creating a new Godot Game Using this Tool Creates a Main.CS file with 24 errors and tons of errors in CI/CD pipeline

### ISSUE THREAD

**Issue by cobriensr** [chickensoft-games/GodotGameTemplate#1] opened 2024-04-08 21:36 UTC
I apologize if this is a bit much, but trying to learn Godot and setup a project, use C#, etc. All of these errors are a bit daunting as I'm not exactly sure where to start to correct these.

Steps followed:

To install GodotEnv, run the following:

dotnet tool install --global Chickensoft.GodotEnv

🦾 Installing with GodotEnv

You can install Godot automatically by specifying a Godot version the way it appears [here](https://www.nuget.org/packages/GodotSharp/).

godotenv godot install 4.2.1

✨ Creating Godot Projects

Chickensoft provides a few dotnet new templates to help you quickly create a C# projects for use with Godot 4.

Now that you've configured your environment (and hopefully rebooted since then), you should be able to use the dotnet tool from your terminal to be able to install Chickensoft's development templates.

dotnet new install Chickensoft.GodotGame
dotnet new install Chickensoft.GodotPackage

To create a new game, simply run the following commands and open the resulting directory in Godot and VSCode.

dotnet new chickengame --name "MyGameName" --param:author "My Name"

cd MyGameName
dotnet restore

dotnet --version
**8.0.203**

Main.cs file:

```
namespace FirstGodotGame;

using Godot;

#if DEBUG
using System.Reflection;
using Chickensoft.GoDotTest;
#endif

// This entry-point file is responsible for determining if we should run tests.
//
// If you want to edit your game's main entry-point, please see Game.tscn and
// Game.cs instead.

public partial class Main : Node2D {
  #if DEBUG
  public TestEnvironment Environment = default!;
#endif
  
  public override void _Ready() {
    #if DEBUG
    // If this is a debug build, use GoDotTest to examine the
    // command line arguments and determine if we should run tests.
    Environment = TestEnvironment.From(OS.GetCmdlineArgs());
    if (Environment.ShouldRunTests) {
      CallDeferred("RunTests");
      return;
    }
  }
#endif
    
    // If we don't need to run tests, we can just switch to the game scene.
    CallDeferred("RunScene");
  }

  #if DEBUG
  private void RunTests()
    => _ = GoTest.RunTests(Assembly.GetExecutingAssembly(), this, Environment);
#endif
  
  private void RunScene()
    => GetTree().ChangeSceneToFile("res://src/Game.tscn");
}
```

Errors:

```
[{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "CS1520",
		"target": {
			"$mid": 1,
			"external": "https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS1520%29",
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS1520)"
		}
	},
	"severity": 8,
	"message": "Method must have a return type",
	"startLineNumber": 33,
	"startColumn": 5,
	"endLineNumber": 33,
	"endColumn": 17
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "CS0501",
		"target": {
			"$mid": 1,
			"external": "https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS0501%29",
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS0501)"
		}
	},
	"severity": 8,
	"message": "'Main.Main()' must declare a body because it is not marked abstract, extern, or partial",
	"startLineNumber": 33,
	"startColumn": 5,
	"endLineNumber": 33,
	"endColumn": 17
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "CS1001",
		"target": {
			"$mid": 1,
			"external": "https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS1001%29",
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS1001)"
		}
	},
	"severity": 8,
	"message": "Identifier expected",
	"startLineNumber": 33,
	"startColumn": 18,
	"endLineNumber": 33,
	"endColumn": 28
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "CS0116",
		"target": {
			"$mid": 1,
			"external": "https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS0116%29",
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS0116)"
		}
	},
	"severity": 8,
	"message": "A namespace cannot directly contain members such as fields, methods or statements",
	"startLineNumber": 37,
	"startColumn": 16,
	"endLineNumber": 37,
	"endColumn": 24
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "CS0119",
		"target": {
			"$mid": 1,
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS0119)"
		}
	},
	"severity": 8,
	"message": "'Environment' is a type, which is not valid in the given context",
	"startLineNumber": 38,
	"startColumn": 67,
	"endLineNumber": 38,
	"endColumn": 78
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "CS0103",
		"target": {
			"$mid": 1,
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS0103)"
		}
	},
	"severity": 8,
	"message": "The name 'GetTree' does not exist in the current context",
	"startLineNumber": 42,
	"startColumn": 8,
	"endLineNumber": 42,
	"endColumn": 15
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "CS1022",
		"target": {
			"$mid": 1,
			"external": "https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS1022%29",
			"path": "/query/roslyn.query",
			"scheme": "https",
			"authority": "msdn.microsoft.com",
			"query": "appId=roslyn&k=k(CS1022)"
		}
	},
	"severity": 8,
	"message": "Type or namespace definition, or end-of-file expected",
	"startLineNumber": 43,
	"startColumn": 1,
	"endLineNumber": 43,
	"endColumn": 2
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 15,
	"startColumn": 37,
	"endLineNumber": 16,
	"endColumn": 3
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 17,
	"startColumn": 49,
	"endLineNumber": 18,
	"endColumn": 1
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 19,
	"startColumn": 1,
	"endLineNumber": 20,
	"endColumn": 3
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 20,
	"startColumn": 34,
	"endLineNumber": 21,
	"endColumn": 5
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 22,
	"startColumn": 62,
	"endLineNumber": 23,
	"endColumn": 5
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 23,
	"startColumn": 68,
	"endLineNumber": 24,
	"endColumn": 5
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 29,
	"startColumn": 4,
	"endLineNumber": 30,
	"endColumn": 1
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 31,
	"startColumn": 1,
	"endLineNumber": 32,
	"endColumn": 5
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 32,
	"startColumn": 76,
	"endLineNumber": 33,
	"endColumn": 5
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0040",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0040",
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0040",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Accessibility modifiers required",
	"startLineNumber": 33,
	"startColumn": 5,
	"endLineNumber": 33,
	"endColumn": 17
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 33,
	"startColumn": 30,
	"endLineNumber": 34,
	"endColumn": 3
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 34,
	"startColumn": 4,
	"endLineNumber": 36,
	"endColumn": 3
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 37,
	"startColumn": 1,
	"endLineNumber": 37,
	"endColumn": 3
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 37,
	"startColumn": 26,
	"endLineNumber": 38,
	"endColumn": 5
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 38,
	"startColumn": 80,
	"endLineNumber": 39,
	"endColumn": 1
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 40,
	"startColumn": 1,
	"endLineNumber": 41,
	"endColumn": 3
},{
	"resource": "/C:/Users/Charl/Documents/GameDev/FirstGodotGame/src/Main.cs",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": {
		"value": "IDE0055",
		"target": {
			"$mid": 1,
			"external": "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"path": "/dotnet/fundamentals/code-analysis/style-rules/ide0055",
			"scheme": "https",
			"authority": "learn.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Fix formatting",
	"startLineNumber": 41,
	"startColumn": 26,
	"endLineNumber": 42,
	"endColumn": 5
}]
```

Also experiencing errors in CI/CD  pipeline in Github Actions:

Generate .Net Bindings:

```
Run godot --headless --build-solutions --quit || exit 0
Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org/
 
WARNING: Custom cursor shape not supported by this display server.
     at: cursor_set_custom_image (servers/display_server.cpp:505)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)
ERROR: Timer was not added to the SceneTree. Either add it or set autostart to true.
   at: start (scene/main/timer.cpp:109)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
```
   
Run Tests in Godot:
   
   ```
Run xvfb-run godot --audio-driver Dummy --rendering-driver vulkan --run-tests --quit-on-finish --coverage
  
Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org/
Vulkan API 1.3.274 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.7, 256 bits)
 
GoTest: > ^^ >> Started testing! :3
GoTest: > ^^ >> GameTest > Test suite started! :3
GoTest: > ^^ >> GameTest::TestButtonUpdatesCounter [Test] > Test started! :3
GoTest: > OK >> GameTest::TestButtonUpdatesCounter [Test] > Test passed! :)
GoTest: > OK >> GameTest > Test suite finished! :D
GoTest: > OK >> Finished testing! :D
GoTest: > OK >> Test results: Passed: 1 | Failed: 0 | Skipped: 0
ERROR: BUG: Unreferenced static string to 0: Physics2DConstraintSolveIslands
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: Physics2DConstraintSetup
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: ShaderCompilation
   at: unref (core/string/string_name.cpp:127)
WARNING: A Thread object is being destroyed without its completion having been realized.
Please call wait_to_finish() on it to ensure correct cleanup.
     at: ~Thread (core/os/thread.cpp:102)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: BUG: Unreferenced static string to 0: current_animation_changed
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: GodotPhysicsDirectSpaceState2D
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: gui_focus_changed
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: frame_post_draw
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: SceneReplicationInterface
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: bus_renamed
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: node_changed
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: SceneCacheInterface
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ThemeContext
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: SceneRPCInterface
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: animation_player_changed
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: fallback_changed
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: animation_libraries_updated
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: animation_list_changed
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: caches_cleared
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: button_down
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: button_up
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: child_entered_tree
   at: unref (core/string/string_name.cpp:129)
Finished running tests in Godot with emulated vulkan graphics.
```

**Comment by jolexxa** [comment] 2024-08-19 14:03
Closing since I haven't been able to reproduce

**Closed as completed by jolexxa** 2024-08-19 14:03 UTC
